### Numpy Array

In [1]:
#Importing Numpy
import numpy as np

In [5]:
a = np.array([1,2,3,5,7])
b = np.array((2,3,5),dtype='f') #define datatype by 'dtype=' and 'f' is float
print(a)
print(type(a))
print(b)
print(type(b))


[1 2 3 5 7]
<class 'numpy.ndarray'>
[2. 3. 5.]
<class 'numpy.ndarray'>


In [8]:
print(a.dtype) #default datatype in numpy array

int64


In [9]:
print(b.dtype)

float32


### Numpy Dimensions

In [13]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim) #number of dimensions

2


In [14]:
print(a[0,2])

3


In [17]:
b = np.array([[1,2,3,-1],[2,4,5,9]])
b[1,2]

5

In [19]:
C = np.array([[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[-0,-0,1]]])
print(C.ndim)

3


In [23]:
C[1,0,1]

-2

### Numpy Shape

In [26]:
B = np.array([[1,2,3,-1],[2,4,5,9]])
print(B.shape)

(2, 4)


In [25]:
C = np.array([[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[-0,-0,1]]])
print(C.shape)

(2, 3, 3)


In [34]:
print(C.size)   #total number of elements. 2*3*3 = 18

18


In [35]:
print(C.nbytes)  #total number of bytes this array allocates

144


In [30]:
print(C.shape[0])

2


In [31]:
A = np.array([2])
A.ndim

1

In [32]:
B = np.array(4)
B.ndim

0

### Numpy(np.arange,reshape,random)

In [37]:
A = np.arange(50)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [40]:
A = np.arange(20,100,3) #start,stop and step size
print(A)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


In [41]:
print(range(10))

range(0, 10)


In [43]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [45]:
A = np.random.permutation(np.arange(10))
print(A)

[7 5 0 2 9 1 6 3 8 4]


In [48]:
np.random.randint(20,30) #random integer between 20 and 30

25